// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchUserRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUserRequest) Reset()         { *m = SearchUserRequest{} }
func (m *SearchUserRequest) String() string { return proto.CompactTextString(m) }
func (*SearchUserRequest) ProtoMessage()    {}
func (*SearchUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *SearchUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserRequest.Unmarshal(m, b)
}
func (m *SearchUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserRequest.Marshal(b, m, deterministic)
}
func (m *SearchUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserRequest.Merge(m, src)
}
func (m *SearchUserRequest) XXX_Size() int {
	return xxx_messageInfo_SearchUserRequest.Size(m)
}
func (m *SearchUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserRequest proto.InternalMessageInfo

func (m *SearchUserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SearchUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type SearchUserResponse struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Married              bool     `protobuf:"varint,3,opt,name=married,proto3" json:"married,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUserResponse) Reset()         { *m = SearchUserResponse{} }
func (m *SearchUserResponse) String() string { return proto.CompactTextString(m) }
func (*SearchUserResponse) ProtoMessage()    {}
func (*SearchUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *SearchUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserResponse.Unmarshal(m, b)
}
func (m *SearchUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserResponse.Marshal(b, m, deterministic)
}
func (m *SearchUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserResponse.Merge(m, src)
}
func (m *SearchUserResponse) XXX_Size() int {
	return xxx_messageInfo_SearchUserResponse.Size(m)
}
func (m *SearchUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserResponse proto.InternalMessageInfo

func (m *SearchUserResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SearchUserResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SearchUserResponse) GetMarried() bool {
	if m != nil {
		return m.Married
	}
	return false
}

func init() {
	proto.RegisterType((*SearchUserRequest)(nil), "grpc.SearchUserRequest")
	proto.RegisterType((*SearchUserResponse)(nil), "grpc.SearchUserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56, 0x72, 0xe4, 0x12,
	0x0c, 0x4e, 0x4d, 0x2c, 0x4a, 0xce, 0x08, 0x2d, 0x4e, 0x2d, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x11, 0x12, 0xe3, 0x62, 0x03, 0x29, 0xf4, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e,
	0x82, 0xf2, 0x84, 0x44, 0xb8, 0x58, 0x0b, 0x32, 0xf2, 0xf3, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35,
	0x38, 0x83, 0x20, 0x1c, 0xa5, 0x28, 0x2e, 0x21, 0x64, 0x23, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53,
	0x71, 0x9a, 0x21, 0xc4, 0xc5, 0x92, 0x9c, 0x59, 0x52, 0x09, 0x35, 0x02, 0xcc, 0x16, 0x92, 0xe0,
	0x62, 0xcf, 0x4d, 0x2c, 0x2a, 0xca, 0x4c, 0x4d, 0x91, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x08, 0x82,
	0x71, 0x8d, 0x3c, 0xb9, 0xb8, 0x10, 0x66, 0x0b, 0x59, 0x73, 0xb1, 0x41, 0x78, 0x42, 0xe2, 0x7a,
	0x20, 0xd7, 0xeb, 0x61, 0x38, 0x5d, 0x4a, 0x02, 0x53, 0x02, 0xe2, 0xa0, 0x24, 0x36, 0xb0, 0xb7,
	0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x03, 0x4c, 0xa9, 0x04, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchUserClient is the client API for SearchUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchUserClient interface {
	Search(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error)
}

type searchUserClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchUserClient(cc grpc.ClientConnInterface) SearchUserClient {
	return &searchUserClient{cc}
}

func (c *searchUserClient) Search(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error) {
	out := new(SearchUserResponse)
	err := c.cc.Invoke(ctx, "/grpc.SearchUser/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchUserServer is the server API for SearchUser service.
type SearchUserServer interface {
	Search(context.Context, *SearchUserRequest) (*SearchUserResponse, error)
}

// UnimplementedSearchUserServer can be embedded to have forward compatible implementations.
type UnimplementedSearchUserServer struct {
}

func (*UnimplementedSearchUserServer) Search(ctx context.Context, req *SearchUserRequest) (*SearchUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterSearchUserServer(s *grpc.Server, srv SearchUserServer) {
	s.RegisterService(&_SearchUser_serviceDesc, srv)
}

func _SearchUser_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchUserServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.SearchUser/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchUserServer).Search(ctx, req.(*SearchUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchUser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.SearchUser",
	HandlerType: (*SearchUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchUser_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
